### ISSUE TITLE
Problem on writing to a file

### ISSUE THREAD

**Issue by masoudr** [greiman/PetitFS#2]
Hi,
I'm trying to write a string to an empty file in the root of SD but the file is empty and all function return `FR_OK`
here is a simple example

```
#include "PetitFS.h"
#include "PetitSerial.h"

PetitSerial PS;
#define Serial PS

// The SD chip select pin is currently defined as 10
// in pffArduino.h.  Edit pffArduino.h to change the CS pin.

FATFS fs;

void setup()
{
    Serial.begin(9600);
    char* buf = "Hello World!\r\n";
    pf_mount(&fs);
    pf_open("TEST.TXT");
    UINT n;

Serial.print("Buff:");
Serial.println(buf);
pf_write(buf,strlen(buf),&n);
pf_write(0,0,&n);
Serial.println("Done");
}
void loop() {}
```
I think I am missing some steps in [the manual](http://elm-chan.org/fsw/ff/pf/write.html).
EDIT:
I fixed it with just putting a large dummy text file. but my problem is how can I append to end of file is there any workaround for that?
Thanks.

**Comment by greiman** [comment]
You can't write an empty file or extend a file.  Just rewrite an existing file.

See this on "the manual" page that you linked.

> Description
> 
> The write function has some restrictions listed below:
> 
>     Cannot create file. Only existing file can be written.
>     Cannot expand file size.
>     Cannot update time stamp of the file.
>     Write operation can start/stop on the sector boundary only.

**Comment by masoudr** [comment]
Thanks, I want to use this library to put some logs into SD. But I cant overwrite my existing data. I was wondering if there is any method or trick to get around this issue. I thought about doing this:
1. put some sample files into sd and try to write on them one by one.
2. after each write save the last sector flag (`fs.fptr`)into EEPROM for example.
3. on boot check the last sector of wrote on last time and use `pf_lseek` to get to the last sector
4. continue to write to file until the last sector of the file.
5. go to the next file and repeat.
I think this method might be a little dirty and maybe there is another solution.

**Comment by greiman** [comment]
I can't help.  I ported this library and found too many limitations so I don't use it.

**Comment by masoudr** [comment]
@greiman Thanks for your help.
